# Generated by Django 5.0.4 on 2024-10-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='line_friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='line_management.linefriend'),
            preserve_default=False,
        ),
    ]
