# Generated by Django 5.0.4 on 2024-10-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0005_alter_linesettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefriend',
            name='line_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_friends', to='line_management.linesettings'),
        ),
    ]
