# Generated by Django 5.0.4 on 2024-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0006_alter_linefriend_line_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesettings',
            name='liff_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
