# Generated by Django 5.0.4 on 2024-10-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0009_alter_linesettings_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linesettings',
            name='destination',
        ),
    ]
