# Generated by Django 5.0.4 on 2024-10-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0014_alter_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
