# Generated by Django 5.0.4 on 2024-10-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0006_alter_linefriend_line_settings'),
        ('score_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresetting',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_settings', to='line_management.tag'),
        ),
    ]
