# Generated by Django 5.0.4 on 2024-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0002_alter_scoresetting_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
