# Generated by Django 5.0.4 on 2024-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0007_shortenedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
