# Generated by Django 5.0.4 on 2024-08-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0008_link_short_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortenedLink',
        ),
    ]
