# Generated by Django 5.0.4 on 2024-08-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0009_delete_shortenedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresetting',
            name='tracking_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
