# Generated by Django 5.0.4 on 2024-08-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0010_scoresetting_tracking_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresetting',
            name='tracking_link',
        ),
    ]
