# Generated by Django 5.0.4 on 2024-08-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0011_remove_scoresetting_tracking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresetting',
            name='tracking_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
