# Generated by Django 5.0.4 on 2024-10-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0012_scoresetting_tracking_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_code',
        ),
    ]
