# Generated by Django 5.0.4 on 2024-10-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0014_remove_userscore_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
